#list
li=[1,89,47,68,56,73,922,89,566,56]
print("for printing full list")
print(li)
print()
print("inserting 25 next to second item")
li.insert(2,25)
print(li)
print()
print("removing 68")
li.remove(68)
print(li)
print()
print("adding another item to the list")
li.append(99)
print(li)
print()
print("adding another list to the list")
li1=[56,34,6785,5678,34,89,00]
li.append(li1)
print(li)
print()
print("4th item from the beginning",li[3])
print()
print("3rd item from the last",li[-3])
print()
print("no.of items", len(li))
print()
print("repeatition of 56", li.count(56))

