from tkinter import *
from tkinter import ttk

def out_put ():
      nam=n5.get()
      pri=n1.get()
      qty=s.get()
      nt_amt=float(pri)*float(qty)
      l=[nam,pri,qty,nt_amt]
      view.insert("",'end',values=l)

win=Tk()
win.geometry("1080x1080")
labl_n=Label(win,text="Enter Name of the product")
labl_n.grid(row=0,column=0,columnspan=2)
n5=Entry(win,width=35)
n5.grid(row=0,column=3)
labl=Label(win,text="Enter rate")
labl.grid(row=1,column=0,columnspan=2)
n1=Entry(win,width=35)
n1.grid(row=1,column=3)
labl1=Label(win,text="select quantity")
labl1.grid(row=2,column=0,columnspan=5)
s=StringVar()
s.set("1")
r1=Radiobutton(win,text="1",value="1",variable=s)
r1.grid(row=3,column=0)
r2=Radiobutton(win,text="2",value="2",variable=s)
r2.grid(row=3,column=1)
r3=Radiobutton(win,text="3",value="3",variable=s)
r3.grid(row=3,column=2)
r4=Radiobutton(win,text="4",value="4",variable=s)
r4.grid(row=3,column=3)
r5=Radiobutton(win,text="5",value="5",variable=s)
r5.grid(row=3,column=4)
but=Button(win,text="output",command=out_put)
but.grid(row=4,column=0,columnspan=5)
view=ttk.Treeview(win,columns=("c1","c2","c3","c4"),show="headings")
view.grid(row=5,column=0,columnspan=5)
view.heading("#1",text="Name")
view.heading("#2",text="Rate")
view.heading("#3",text="Quantity")
view.heading("#4",text="Net amount")
